config/routes.rb
Rails.application.routes.draw do
  get 'users/index'
  post 'users/import'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  require 'csv'

  def self.import(file)
    data=CSV.read(file, { encoding: "UTF-8", headers: true, header_converters: :symbol, converters: :all})
    raise Exception.new('Missing required file') unless data
    users_data = data.map { |d| d.to_hash }

    users_data.each do |employee|
      employee[:gross_income]= calculate_gross_income(employee.dig(:annual_salary) || 0)
      employee[:income_tax]= calculate_income_tax(employee.dig(:annual_salary)|| 0)
      employee[:net_income]=employee[:gross_income]-employee[:income_tax]
      employee[:super]= (employee[:gross_income] * (validate_values(employee.dig(:super_rate)||0))).round
      User.create! employee
    end
  end

  def self.export
    CSV.generate do |csv|
      csv << column_names
      all.each do |user|
        csv << user.attributes.values_at(*column_names)
      end
    end
  end

  private

  def self.validate_values(val)
    case val
    when String
      val.include?("%") ? val.to_f/100 : (val.delete("$,").to_f)
    when Float
      val
    else
      0
    end
  end
  
  def self.calculate_gross_income(annual_salary)
      validate_values(annual_salary)/12
  end

  def self.calculate_income_tax(annual_salary)
    calculation= case validate_values(annual_salary)
                 when 0..18000
                   0
                 when 18201..37000
                   (((annual_salary-18200)*0.19)/12).round
                 when 37001..87000
                   ((3572 + ((annual_salary-37000)*0.325))/12).round
                 when 87001..180000
                   ((19822 + ((annual_salary-87000)*0.37))/12).round
                 else
                   ((54232 + ((annual_salary-18200)*0.19))/12).round
                 end

    calculation
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users=User.all

    respond_to do |format|
      format.html
      format.csv { send_data @users.export }
      format.xls
    end


  end

  def import
    User.import(params[:file].path)
    redirect_to users_index_path, notice: 'File Imported'
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Payslip</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/_import.html.erb
<h1>Import</h1>
<%= form_tag users_import_path, multipart: true do %>
  <%= file_field_tag :file %>
  <%= submit_tag "Import CSV" %>
<% end %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
  <tr>
    <th>First name</th>
    <th>Last name</th>
    <th>Annual salary</th>
    <th>Super rate</th>
    <th>Payment start date</th>
    <th>Gross income</th>
    <th>Income tax</th>
    <th>Net income</th>
    <th>Super</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @users.each do |user| %>
    <tr>
      <td><%= user.first_name %></td>
      <td><%= user.last_name %></td>
      <td><%= user.annual_salary %></td>
      <td><%= user.super_rate %></td>
      <td><%= user.payment_start_date %></td>
      <td><%= user.gross_income %></td>
      <td><%= user.income_tax %></td>
      <td><%= user.net_income %></td>
      <td><%= user.super %></td>
  <% end %>
    </tr>
  <%if @users	%>
   <tr> <td><%= link_to 'Export', users_index_path(format:"csv") %></td> </tr>
  <% end	  %>
  </tbody>
</table>

<%= render 'import', user: @user %>